import json, os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(BASE_DIR, "config.json")

with open(CONFIG_PATH, encoding="utf-8") as f:
    CONFIG = json.load(f)

HOMETAX_URL_MAIN = CONFIG["HOMETAX_URL"]["main"]
HOMETAX_URL_DEDUCTION_CHANGE = CONFIG["HOMETAX_URL"]["deduction_change"]
HOMETAX_URL_DEDUCTION_CHECK = CONFIG["HOMETAX_URL"]["deduction_check"]

XPATH_LOGIN = CONFIG["XPATH_LOGIN"]
XPATH_RES_NO = CONFIG["XPATH_RES_NO"]
XPATH_ALL_SELECT_CHECKBOX = CONFIG["XPATH_DEDUCTION"]["all_select_checkbox"]
XPATH_DEDUCTION_CHANGE = CONFIG["XPATH_DEDUCTION"]["change"]
XPATH_PAGE_NAVIGATION = CONFIG["XPATH_DEDUCTION"]["page_navigation"]

CLICK_SCRIPT = CONFIG["CLICK_SCRIPT"]
CHROME_OPTIONS_ARGS = CONFIG["CHROME_OPTIONS_ARGS"]
EXCEL_FILE_TYPES = CONFIG["EXCEL_FILE_TYPES"]
PAGE_BLOCK_SIZE = CONFIG["PAGE_BLOCK_SIZE"]
ROW_PER_PAGE = CONFIG["ROW_PER_PAGE"]
